apiVersion: v1
kind: Template
metadata:
  annotations:
    description: Gitlab is a self-hosted Git service
  creationTimestamp: null
  name: gitlab
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations: {}
    labels:
      project: gitlab
      provider: fabric8
    name: gitlab
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      project: gitlab
      provider: fabric8
    type: LoadBalancer
- apiVersion: v1
  kind: Service
  metadata:
    annotations: {}
    labels:
      project: gitlab
      provider: fabric8
    name: gitlab-ssh
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 22
      protocol: TCP
      targetPort: 22
    selector:
      project: gitlab
      provider: fabric8
- apiVersion: v1
  kind: Route
  metadata:
    name: gitlab
  spec:
    host: ${APPLICATION_DOMAIN}
    to:
      kind: Service
      name: gitlab
- apiVersion: v1
  kind: ReplicationController
  metadata:
    annotations:
      fabric8.io/build-id: "6"
      fabric8.io/git-branch: release-v2.2.104
      fabric8.io/git-commit: df8e36b08230aa1698bb6c61012911c9662fc23d
    labels:
      group: io.fabric8.devops.apps
      project: gitlab
      provider: fabric8
      version: 2.2.104
    name: gitlab
  spec:
    replicas: 1
    selector:
      group: io.fabric8.devops.apps
      project: gitlab
      provider: fabric8
      version: 2.2.104
    template:
      metadata:
        annotations: {}
        labels:
          group: io.fabric8.devops.apps
          project: gitlab
          provider: fabric8
          version: 2.2.104
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: GITLAB_OMNIBUS_CONFIG
            value: ${GITLAB_OMNIBUS_CONFIG}
          - name: GITLAB_ADMIN_USER_PASSWORD
            value: ${JENKINS_GITLAB_PASSWORD}
          - name: GITLAB_ADMIN_USER_EMAIL
            value: ${JENKINS_GITLAB_EMAIL}
          - name: GITLAB_ADMIN_USER_NAME
            value: ${JENKINS_GITLAB_USER}
          - name: GITLAB_URL
            value: ${GITLAB_URL}
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: gitlab/gitlab-ce
          imagePullPolicy: IfNotPresent
          name: gitlab
          ports:
          - containerPort: 22
            name: ssh
          - containerPort: 80
            name: http
          - containerPort: 443
            name: https
          securityContext: {}
#          volumeMounts:
#          - mountPath: "/var/opt/gitlab"
#            name: gitlab-data
        imagePullSecrets: []
        nodeSelector: {}
#        volumes:
 #       - name: gitlab-data
 #         persistentVolumeClaim:
 #           claimName: gitlab-data
parameters:
- description: Additional environement parameters to pass to Omnibus, makes possible
    to configure GitLab external URL, database configuration or any other option  from
    Omnibus like gitlab_rails['smtp_address'] = "smtp.gmail.com";
  name: GITLAB_OMNIBUS_CONFIG
- description: The exposed hostname that will route to the Gitlab service, if left
    blank a value will be defaulted.
  name: APPLICATION_DOMAIN
- description: The email address of the Jenkins user on Gitlab
  name: JENKINS_GITLAB_EMAIL
  value: gitlab@fabric8.local
- description: The user name for Jenkins to login to Gitlab
  name: JENKINS_GITLAB_USER
  value: jenkins
- description: The GitLab server URL
  name: GITLAB_URL
  value: gitlab.vagrant.f8
- description: The password for Jenkins to login to Gitlab
  name: JENKINS_GITLAB_PASSWORD
  value: RedHat$1
