apiVersion: v1
kind: Template
metadata:
  annotations:
    description: |
      Gogs is a self-hosted Git service written in Go.
  creationTimestamp: null
  name: gogs
objects:
- apiVersion: v1
  data:
    password: UmVkSGF0JDE=
    username: Z29nc2FkbWlu
  kind: Secret
  metadata:
    annotations: {}
    labels: {}
    name: gogs-https-${KUBERNETES_ADMIN_USER}
    namespace: user-secrets-source-${KUBERNETES_ADMIN_USER}
- apiVersion: v1
  kind: OAuthClient
  metadata:
    annotations: {}
    labels: {}
    name: gogs
  redirectURIs:
  - http://localhost:3000
  - http://gogs.${DOMAIN}
  - https://gogs.${DOMAIN}
  - http://${APPLICATION_DOMAIN}
  - https://${APPLICATION_DOMAIN}
- apiVersion: v1
  kind: Service
  metadata:
    annotations: {}
    labels:
      project: gogs
    name: gogs
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
    selector:
      project: gogs
    type: LoadBalancer
- apiVersion: v1
  kind: Service
  metadata:
    annotations: {}
    labels:
      project: gogs
    name: gogs-ssh
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 22
      protocol: TCP
      targetPort: 22
    selector:
      project: gogs
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
    labels:
      project: gogs
    name: gogs
  spec:
    replicas: 1
    selector:
      project: gogs
    template:
      metadata:
        annotations: {}
        labels:
          project: gogs
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: GOGS_SERVER__ROOT_URL
            value: ${GOGS_SERVER_PROTOCOL}://${GOGS_SERVER_DOMAIN}
          - name: ADMIN_USER_EMAIL
            value: ${JENKINS_GOGS_EMAIL}
          - name: ADMIN_USER_PASSWORD
            value: ${JENKINS_GOGS_PASSWORD}
          - name: GOGS_SERVER__PROTOCOL
            value: ${GOGS_SERVER_PROTOCOL}
          - name: GOGS_OAUTH_OPENSHIFT__ENABLED
            value: "true"
          - name: ADMIN_USER_CREATE
            value: "true"
          - name: GOGS_OAUTH_OPENSHIFT__TOKEN_URL
            value: https://${DOMAIN}:8443/oauth/token
          - name: GOGS_OAUTH_OPENSHIFT__SCOPES
            value: https://${DOMAIN}:8443/console/user
          - name: GOGS_OAUTH_OPENSHIFT__AUTH_URL
            value: https://${DOMAIN}:8443/oauth/authorize
          - name: GOGS_WEBHOOK__TASK_INTERVAL
            value: "true"
          - name: GOGS_WEBHOOK__SKIP_TLS_VERIFY
            value: "true"
          - name: GOGS_SERVER__DOMAIN
            value: ${GOGS_SERVER_DOMAIN}
          - name: ADMIN_USER_NAME
            value: ${JENKINS_GOGS_USER}
          - name: GOGS_OAUTH_TWITTER__ENABLED
            value: "false"
          - name: GOGS_OAUTH__ENABLED
            value: "true"
          - name: KUBERNETES_ADMIN_USER
            value: ${KUBERNETES_ADMIN_USER}
          - name: GOGS_OAUTH_OPENSHIFT__CLIENT_ID
            value: gogs
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: fabric8/gogs:0.6.1
          imagePullPolicy: IfNotPresent
          name: gogs
          ports:
          - containerPort: 22
            name: ssh
          - containerPort: 3000
            name: http
          securityContext: {}
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        volumes: []
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    host: ${APPLICATION_DOMAIN}
    to:
      kind: Service
      name: ${APPLICATION_NAME}

parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: gogs
- description: 'Custom hostname for service routes.  Leave blank for default hostname,
    e.g.: <application-name>.<project>.<default-domain-suffix>'
  name: APPLICATION_DOMAIN
- description: The email address of the Jenkins user on Gogs
  name: JENKINS_GOGS_EMAIL
  value: gogsadmin@akrambenaissi.com
- description: The user name for Jenkins to login to Gogs
  name: JENKINS_GOGS_USER
  value: gogsadmin
- description: The gogs server name
  name: GOGS_SERVER_DOMAIN
  value: paas.akrambenaissi.com
- description: The protocol for gogs to use; either http or https
  name: GOGS_SERVER_PROTOCOL
  value: http
- description: The password for Jenkins to login to Gogs
  name: JENKINS_GOGS_PASSWORD
  value: RedHat$1
- description: The default Kubernetes admin user
  name: KUBERNETES_ADMIN_USER
  value: admin
- description: The domain applications are installed on
  name: DOMAIN
  value: paas.akrambenaissi.com
